### ISSUE TITLE
Bug: Mod Loader places png file where the mod can't find it.

### ISSUE THREAD

**Issue by JamieRCHI** [GreyHak/dsp-color-drones#1]
What I am guessing is that mods used to be installed in SteamLibrary\steamapps\common\Dyson Sphere Program\BepInEx\config. 

Now, the Mod Loader installs mods at AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\config. 

So, on my system the BepinEX\config folder does not exist. As a temporary fix I just created the folder and copied the .png file there. This works.

I am not in a hurry for this to be fixed, due to the simple work-around. I would assume that this might be a low priority kind of thing.

Thanks for this mod and looking at this issue.

**Comment by GreyHak** [comment]
@JamieRCHI Thank you for the report.
When r2modman was working previously it was also installing mods to a location other than SteamLibrary\steamapps\common\Dyson Sphere Program\BepInEx\config.  I'm unsure what has changed, but I have been able to confirm the compatibility issue with ebkr-r2modman-3.1.17.  The mod loads the .png from a relative location.  So I suspect that the working directory that r2modman now uses is different than before.  (I'm surprised the prior working directory had even worked.)
This means I need to either tell r2modman the proper location to put the file, or the mod needs to be able to find the one r2modman installed.  Unfortunately I don't know how to do either of those.  I'll look into it.

**Comment by GreyHak** [comment]
AshHat on Discord was able to help to determine how to find the config file, a solution which will when manually installed or run through r2modman.

**Comment by GreyHak** [comment]
Config file path fixed in v1.0.2.  Now works as expected when run/installed manually or when using r2modman.  Thank you again for the report @JamieRCHI

**Comment by JamieRCHI** [comment]
Cool. 👍
